---
title: "Chlorophyll Data integration and explotraion"
format: html
Author: Emily Richardson, TBD
---

# This workbook contains code to integrate pre-cleaned chlorophyll data. See 01-prefixed notebooks for cleaning steps.

## Load Packages
```{r}
library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)
library(sf)
library(leaflet)
library(leaflet.extras2)
library(scales)
library(crosstalk)
library(geojsonsf)
library(jsonlite)
```

## Read in data and keep only dates that fall within the range of continous monitoring data

```{r}
#Continuous monitoring
cm_data <- read.csv("data//01_processed//01_chl_cm_daytime_avg.csv")
cm_data <- cm_data %>% select(-X)
maxdate <- as.Date(max(cm_data$date))
mindate <- as.Date(min(cm_data$date))

#ScienceBase
sb_data <- read.csv("data//01_processed//01_chl_sciencebase.csv")
sb_data <- sb_data %>% 
    mutate(date = as.Date(datetime),
    group = "usgs") %>%
    filter(between(date, mindate, maxdate))

#EMP

iep_data <- read.csv("data//01_processed//01_chl_iep.csv")
iep_data <- iep_data %>% 
  mutate(date = as.Date(date))%>%
  filter(between(date, mindate, maxdate))

#EDI
## TBD

rm(mindate, maxdate)
```

## Combine the data

```{r}
cm_data <- cm_data %>% 
    rename(sample_type = instrument,
    chl_ugl = avg_fchl) %>%
    mutate(date = as.Date(date),
    chl_ugl = round(chl_ugl, 2)) %>% 
    distinct()

sb_data <- sb_data %>%
    select(-datetime) %>%
    mutate(station = NA)%>%
    distinct()

ieprmks <- iep_data %>% filter (!is.na(chla_rmk)) %>% select(chla_rmk, group) %>% distinct() #unclear what the disclaimers are but assuming bad date (outside of reporting limits, etc.) just going to remove them.

iep_data <- iep_data %>%
    filter(is.na(depth)| depth <=2) %>%
    filter(is.na(chla_rmk))%>%
    select(-datetime, -X, -depth, -chla_rmk) %>%
    rename(chl_ugl = chla)%>%     
    mutate(chl_ugl = round(chl_ugl, 2)) %>% 
    distinct()

chl_data <- rbind(cm_data, sb_data, iep_data)
rm(cm_data, sb_data, ieprmks, iep_data)

chl_data <- chl_data %>% filter(!is.na(latitude)) %>% filter(!is.na(longitude)) %>% filter(!is.na(chl_ugl)) %>% distinct()
```

## Visulaize the data

### Convert and clean

```{r}
#Create spatial object
chl_sf <- chl_data %>% 
    st_as_sf(coords = c('longitude', 'latitude'),
             crs = 4326, #WGS84, leaflet demands it.
             remove = FALSE)

#read in shapefile
# read in geoJSON for Delta + Suisun
delta_suisun_sf <- st_read(
  "https://services5.arcgis.com/netd7RBEFAa05HUC/ArcGIS/rest/services/LegalDelta/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson")

nad83_delta_suisun_sf <- st_transform(delta_suisun_sf, crs = 4326)
rm(delta_suisun_sf)

# find sampling locations in Delta + Suisun
chl_delta_suisun_sf <- st_filter(chl_sf, nad83_delta_suisun_sf, .predicate = st_intersects)
rm(chl_sf)

#group by hydrologic cycle
chl_seasonal <- chl_delta_suisun_sf %>%
  mutate(
    year = year(date),
    month = month(date),
    season = case_when(
      month %in% c(10, 11, 12, 1, 2, 3) ~ "Wet",
      month %in% c(4, 5, 6, 7, 8, 9)     ~ "Dry"),
    water_year = if_else(month >= 10, year + 1, year),
    season_date = case_when(
      season == "Wet" ~ as.Date(paste0(water_year, "-01-15")),
      season == "Dry" ~ as.Date(paste0(water_year, "-07-15"))
  ))
```
